version: "0.5"

# Global environment is imported from project .env: $PROJECT/.env
# in container, it's /home/user/tangram/.env

log_location: /tmp/pc.log
log_level: debug

processes:
  web:
    working_dir: /home/user/tangram/web
    command: just tangram-web
    availability:
      restart: "always"

  channel:
    command: /home/user/.cargo/bin/channel --port 2025 --jwt-secret secret
    working_dir: /home/user/tangram

  core/restapi:
    environment:
    command: just tangram-restapi
    working_dir: /home/user/tangram/
    availability:
      restart: "always"

  core/system:
    environment:
      - "UV_PROJECT_ENVIRONMENT=/home/user/.local/share/venvs/tangram"
    working_dir: /home/user/tangram/
    command: env && pwd && uv run -- python -m tangram.system
    availability:
      restart: "always"

  core/aircraft:
    environment:
      - "UV_PROJECT_ENVIRONMENT=/home/user/.local/share/venvs/tangram"
    working_dir: /home/user/tangram/
    command: env && pwd && uv run -- python -m tangram.aircraft
    availability:
      restart: "always"

  core/trail:
    environment:
      - "UV_PROJECT_ENVIRONMENT=/home/user/.local/share/venvs/tangram"
    working_dir: /home/user/tangram/
    command: env && pwd && uv run -- python -m tangram.trail
    availability:
      restart: "always"

  # core/history:
  #   environment:
  #     - "UV_PROJECT_ENVIRONMENT=/home/user/.local/share/venvs/tangram"
  #   working_dir: /home/user/tangram/service
  #   command: env && pwd && uv run -- python -m tangram.history
  #   availability:
  #     restart: "always"
