from typing import Any, final

@final
class DatalinkConfig:
    def __new__(cls, /, redis_url: str, state_vector_expire: int, stream_interval_secs: float) -> DatalinkConfig: ...
    @property
    def redis_url(self, /) -> str: ...
    @redis_url.setter
    def redis_url(self, /, value: str) -> None: ...
    @property
    def state_vector_expire(self, /) -> int: ...
    @state_vector_expire.setter
    def state_vector_expire(self, /, value: int) -> None: ...
    @property
    def stream_interval_secs(self, /) -> float: ...
    @stream_interval_secs.setter
    def stream_interval_secs(self, /, value: float) -> None: ...

def run_datalink(config: DatalinkConfig) -> Any: ...
