verbose = false
interactive = true
serve_port = 8080
prevent_sleep = false
update_position = false
history_expire = 20
redis_url = "redis://redis:6379"

[[sources]]
name = "TU Delft"
airport = "EHRD"
websocket = "ws://feedme.mode-s.org:9876/40128"
