from typing import Any, final

@final
class ChannelConfig:
    def __new__(cls, /, host: str, port: int, redis_url: str, jwt_secret: str, jwt_expiration_secs: int, id_length: int) -> ChannelConfig: ...
    @property
    def host(self, /) -> str: ...
    @host.setter
    def host(self, /, value: str) -> None: ...
    @property
    def id_length(self, /) -> int: ...
    @id_length.setter
    def id_length(self, /, value: int) -> None: ...
    @property
    def jwt_expiration_secs(self, /) -> int: ...
    @jwt_expiration_secs.setter
    def jwt_expiration_secs(self, /, value: int) -> None: ...
    @property
    def jwt_secret(self, /) -> str: ...
    @jwt_secret.setter
    def jwt_secret(self, /, value: str) -> None: ...
    @property
    def port(self, /) -> int: ...
    @port.setter
    def port(self, /, value: int) -> None: ...
    @property
    def redis_url(self, /) -> str: ...
    @redis_url.setter
    def redis_url(self, /, value: str) -> None: ...

def init_tracing_stderr(filter_str: str) -> None: ...
def run(config: ChannelConfig) -> Any: ...
