export default [
  {
    name: 'Default',
    url: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png'
  }, {
    name: 'Colored',
    url: 'http://sgx.geodatenzentrum.de/wmts_topplus_open/tile/1.0.0/web/default/WEBMERCATOR/{z}/{y}/{x}.png'
  }, {
    name: 'Grey',
    url: 'http://sgx.geodatenzentrum.de/wmts_topplus_open/tile/1.0.0/web_grau/default/WEBMERCATOR/{z}/{y}/{x}.png'
  }, {
    name: 'DE',
    url: 'https://tile.openstreetmap.de/{z}/{x}/{y}.png'
  }, {
    name: 'CN',
    url: 'https://tile.osm.ch/switzerland/{z}/{x}/{y}.png'
  }, {
    name: 'France',
    url: 'https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png'
  }, {
    name: 'HOT',
    url: 'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'
  }, {
    name: 'BZH',
    url: 'https://tile.openstreetmap.bzh/br/{z}/{x}/{y}.png'
  }, {
    name: 'OpenTopoMap',
    url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png'
  }, {
    name: 'Dark',
    url: 'https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png'
  }, {
    name: 'White',
    url: 'https://tiles.stadiamaps.com/tiles/alidade_smooth/{z}/{x}/{y}{r}.png'
  }, {
    name: 'Satellite',
    url: 'https://tiles.stadiamaps.com/tiles/alidade_satellite/{z}/{x}/{y}{r}.png'
  }, {
    name: 'Bright',
    url: 'https://tiles.stadiamaps.com/tiles/osm_bright/{z}/{x}/{y}{r}.png'
  }, {
    name: 'Toner',
    url: 'https://tiles.stadiamaps.com/tiles/stamen_toner/{z}/{x}/{y}{r}.png'
  }, {
    name: 'Terrain',
    url: 'https://tiles.stadiamaps.com/tiles/stamen_terrain_background/{z}/{x}/{y}{r}.png'
  }]
