[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tangram"
version = "0.2.0"
description = "A framework for real-time analysis of ADS-B and Mode S surveillance data"
authors = [
  { name = "Xavier Olive", email = "git@xoolive.org" },
  { name = "Junzi Sun", email = "git@junzis.com" },
  { name = "Xiaogang Huang", email = "maple.hl@gmail.com" },
  { name = "Michel Khalaf", email = "khalafmichel98@gmail.com" },
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.115.4",
  "uvicorn>=0.32.0",
  "redis>=5.2.0",
  "httpx>=0.27.2",
  "pydantic-settings>=2.6.1",
  "typer",
  "tomli; python_version < '3.11'",
]

[project.scripts]
tangram = "tangram.__main__:app"

[tool.maturin]
python-source = "src"  # needed for stubgen to output path correctly.
module-name = "tangram._channel"
features = ["python"]