
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# TODO: migrate to maturin, see https://github.com/open-aviation/tangram/issues/36

[project]
name = "tangram"
version = "0.2.0"
description = "A framework for real-time analysis of ADS-B and Mode S surveillance data"
authors = [
  { name = "Xavier Olive", email = "git@xoolive.org" },
  { name = "Junzi Sun", email = "git@junzis.com" },
  { name = "Xiaogang Huang", email = "maple.hl@gmail.com" },
  { name = "Michel Khalaf", email = "khalafmichel98@gmail.com" },
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.115.4",
  "uvicorn>=0.32.0",
  "redis>=5.2.0",
  "httpx>=0.27.2",
  "pydantic-settings>=2.6.1",
  "typer"
]

[project.scripts]
tangram = "tangram.cli:app"

[tool.hatch.build.targets.sdist]
ignore-vcs = true
include = ["dist-frontend/*", "src/*"]

[tool.hatch.build.targets.wheel.force-include]
"dist-frontend" = "tangram/dist-frontend"