from typing import Any, final

@final
class PlanesConfig:
    def __new__(cls, /, redis_url: str, jet1090_channel: str, history_table_name: str, history_control_channel: str, state_vector_expire: int, stream_interval_secs: float, aircraft_db_path: str, history_buffer_size: int, history_flush_interval_secs: int, history_optimize_interval_secs: int, history_optimize_target_file_size: int, history_vacuum_interval_secs: int, history_vacuum_retention_period_secs: int |None, history_checkpoint_interval: int, search_channel: str) -> PlanesConfig: ...
    @property
    def aircraft_db_path(self, /) -> str: ...
    @aircraft_db_path.setter
    def aircraft_db_path(self, /, value: str) -> None: ...
    @property
    def history_buffer_size(self, /) -> int: ...
    @history_buffer_size.setter
    def history_buffer_size(self, /, value: int) -> None: ...
    @property
    def history_checkpoint_interval(self, /) -> int: ...
    @history_checkpoint_interval.setter
    def history_checkpoint_interval(self, /, value: int) -> None: ...
    @property
    def history_control_channel(self, /) -> str: ...
    @history_control_channel.setter
    def history_control_channel(self, /, value: str) -> None: ...
    @property
    def history_flush_interval_secs(self, /) -> int: ...
    @history_flush_interval_secs.setter
    def history_flush_interval_secs(self, /, value: int) -> None: ...
    @property
    def history_optimize_interval_secs(self, /) -> int: ...
    @history_optimize_interval_secs.setter
    def history_optimize_interval_secs(self, /, value: int) -> None: ...
    @property
    def history_optimize_target_file_size(self, /) -> int: ...
    @history_optimize_target_file_size.setter
    def history_optimize_target_file_size(self, /, value: int) -> None: ...
    @property
    def history_table_name(self, /) -> str: ...
    @history_table_name.setter
    def history_table_name(self, /, value: str) -> None: ...
    @property
    def history_vacuum_interval_secs(self, /) -> int: ...
    @history_vacuum_interval_secs.setter
    def history_vacuum_interval_secs(self, /, value: int) -> None: ...
    @property
    def history_vacuum_retention_period_secs(self, /) -> int |None: ...
    @history_vacuum_retention_period_secs.setter
    def history_vacuum_retention_period_secs(self, /, value: int |None) -> None: ...
    @property
    def jet1090_channel(self, /) -> str: ...
    @jet1090_channel.setter
    def jet1090_channel(self, /, value: str) -> None: ...
    @property
    def redis_url(self, /) -> str: ...
    @redis_url.setter
    def redis_url(self, /, value: str) -> None: ...
    @property
    def search_channel(self, /) -> str: ...
    @search_channel.setter
    def search_channel(self, /, value: str) -> None: ...
    @property
    def state_vector_expire(self, /) -> int: ...
    @state_vector_expire.setter
    def state_vector_expire(self, /, value: int) -> None: ...
    @property
    def stream_interval_secs(self, /) -> float: ...
    @stream_interval_secs.setter
    def stream_interval_secs(self, /, value: float) -> None: ...

def init_tracing_stderr(filter_str: str) -> None: ...
def run_planes(config: PlanesConfig) -> Any: ...
